In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
#os.getcwd()

'C:\\Users\\freya\\Downloads\\UpdatedResourceMaterials\\Day2'

In [4]:
df = pd.read_csv("C:/Users/freya/Downloads/UpdatedResourceMaterials/dataFiles/liedetector.csv")
df

X1       X2        X3       X4       X5  X6
0      P_001  3.62160   8.66610  -2.8073 -0.44699   0
1      P_002  4.54590   8.16740  -2.4586 -1.46210   0
2      P_003  3.86600  -2.63830   1.9242  0.10645   0
3      P_004  3.45660   9.52280  -4.0112 -3.59440   0
4      P_005  0.23230  -4.45520   4.5718 -0.98880   0
...      ...      ...       ...      ...      ...  ..
1367  P_1368  0.40614   1.34920  -1.4501 -0.55949   0
1368  P_1369 -1.38870  -4.87730   6.4774  0.34179   0
1369  P_1370 -3.75030 -13.45860  17.5932 -2.77710   0
1370  P_1371 -3.56370  -8.38270  12.3930 -1.28230   0
1371  P_1372 -2.54190  -0.65804   2.6842  1.19520   0

[1372 rows x 6 columns]

In [4]:
df.shape

(1372, 6)

In [5]:
df.columns

Index(['X1', 'X2', 'X3', 'X4', 'X5', 'X6'], dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X1      1372 non-null   object 
 1   X2      1372 non-null   float64
 2   X3      1372 non-null   float64
 3   X4      1372 non-null   float64
 4   X5      1372 non-null   float64
 5   X6      1372 non-null   int64  
dtypes: float64(4), int64(1), object(1)
memory usage: 64.4+ KB


In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
X1 = df["X1"]
X2 = df["X2"]
X3 = df["X3"]
X4 = df["X4"]
X5 = df["X5"]
X6 = df["X6"]

In [9]:
type(X2)

pandas.core.series.Series

In [10]:
print(X2)

0       3.62160
1       4.54590
2       3.86600
3       3.45660
4       0.23230
         ...   
1367    0.40614
1368   -1.38870
1369   -3.75030
1370   -3.56370
1371   -2.54190
Name: X2, Length: 1372, dtype: float64


In [11]:
x1Array = np.array(X1)
x2Array = np.array(X2)
x3Array = np.array(X3)
x4Array = np.array(X4)
x5Array = np.array(X5)
x6Array = np.array(X6)

In [12]:
type(x2Array)

numpy.ndarray

In [13]:
print(x2Array)

[ 3.6216  4.5459  3.866  ... -3.7503 -3.5637 -2.5419]


#### Mean (Average)

In [14]:
print("SUM:", x2Array.sum())
print("Total Numbers:",len(x2Array))
print("Calculated Mean:", x2Array.sum() / len(x2Array))

SUM: 594.9878326999999
Total Numbers: 1372
Calculated Mean: 0.4336646010932944


In [15]:
print("Numpy Mean: ",np.mean(x2Array))

Numpy Mean:  0.4336646010932944


In [16]:
print("Pandas Mean:", X2.mean())

Pandas Mean: 0.4336646010932944


In [17]:
df.mean()

/var/folders/vg/knv8k4t949gbhzdyb1nl_p180000gn/T/ipykernel_13295/3698961737.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()


X2    0.433665
X3    1.922353
X4    1.397627
X5   -1.191657
X6    0.406706
dtype: float64

#### Median (Quntiles)

In [18]:
# Numpy Quantiles
np.quantile(x2Array, [0.0, 0.25, 0.5, 0.75, 1.0])

array([-7.0421  , -1.773   ,  0.49618 ,  2.821475,  6.8248  ])

In [19]:
qArray = np.linspace(0,1,11)
qArray

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [20]:
np.quantile(x2Array, qArray)

array([-7.0421  , -3.30979 , -2.17636 , -1.39701 , -0.404088,  0.49618 ,
        1.273   ,  2.29175 ,  3.42152 ,  4.11793 ,  6.8248  ])

In [21]:
# Pandas Quantile
X2.quantile(qArray)

0.0   -7.042100
0.1   -3.309790
0.2   -2.176360
0.3   -1.397010
0.4   -0.404088
0.5    0.496180
0.6    1.273000
0.7    2.291750
0.8    3.421520
0.9    4.117930
1.0    6.824800
Name: X2, dtype: float64

In [22]:
df.quantile(qArray)

X2         X3         X4        X5   X6
0.0 -7.042100 -13.773100  -5.286100 -8.548200  0.0
0.1 -3.309790  -6.478490  -3.439470 -4.253770  0.0
0.2 -2.176360  -3.387020  -2.245200 -3.028280  0.0
0.3 -1.397010  -0.378269  -0.990028 -1.810030  0.0
0.4 -0.404088   0.725068  -0.196166 -1.079040  0.0
0.5  0.496180   2.319650   0.616630 -0.586650  0.0
0.6  1.273000   3.411800   1.415920 -0.206216  1.0
0.7  2.291750   5.829340   2.526640  0.211706  1.0
0.8  3.421520   7.643080   4.563760  0.549980  1.0
0.9  4.117930   9.435490   7.881250  0.961180  1.0
1.0  6.824800  12.951600  17.927400  2.449500  1.0

#### Mode

In [23]:
np.unique(x2Array, return_counts=True)

(array([-7.0421, -7.0364, -6.9599, ...,  6.0919,  6.5633,  6.8248]),
 array([1, 1, 1, ..., 1, 1, 1]))

In [31]:
(unique, counts) = np.unique(x4Array, return_counts=True)
frequencies = np.asarray((unique, counts)).T

In [32]:
frequencies[frequencies[:, 1].argsort()]

array([[-5.2861,  1.    ],
       [ 2.2215,  1.    ],
       [ 2.2138,  1.    ],
       ...,
       [ 4.5718,  5.    ],
       [ 3.0895,  5.    ],
       [ 1.2421,  5.    ]])

In [30]:
from scipy import stats
m = stats.mode(x4Array)
print(m)

ModeResult(mode=array([1.2421]), count=array([5]))


In [28]:
X2.mode()

0    0.5706
dtype: float64

In [29]:
df.mode()

X1      X2      X3      X4      X5   X6
0     P_001  0.5706 -4.4552  1.2421 -0.9888  0.0
1     P_002     NaN     NaN  3.0895 -0.2957  NaN
2     P_003     NaN     NaN  4.5718     NaN  NaN
3     P_004     NaN     NaN     NaN     NaN  NaN
4     P_005     NaN     NaN     NaN     NaN  NaN
...     ...     ...     ...     ...     ...  ...
1367  P_995     NaN     NaN     NaN     NaN  NaN
1368  P_996     NaN     NaN     NaN     NaN  NaN
1369  P_997     NaN     NaN     NaN     NaN  NaN
1370  P_998     NaN     NaN     NaN     NaN  NaN
1371  P_999     NaN     NaN     NaN     NaN  NaN

[1372 rows x 6 columns]

#### Range

In [33]:
print(np.max(x2Array), np.min(x2Array), np.max(x2Array) - np.min(x2Array))

6.8248 -7.0421 13.8669


In [34]:
print(X2.max(), X2.min(), X2.max() - X2.min())

6.8248 -7.0421 13.8669


In [35]:
minArray = df.min()
maxArray = df.max()

rangeDf = pd.DataFrame({"max": maxArray[1:], "min": minArray[1:]})
rangeDf

max      min
X2   6.8248  -7.0421
X3  12.9516 -13.7731
X4  17.9274  -5.2861
X5   2.4495  -8.5482
X6        1        0

In [36]:
rangeDf['range'] = rangeDf['max'] - rangeDf['min']
rangeDf

max      min    range
X2   6.8248  -7.0421  13.8669
X3  12.9516 -13.7731  26.7247
X4  17.9274  -5.2861  23.2135
X5   2.4495  -8.5482  10.9977
X6        1        0        1

#### Variance and Standard Deviation

Formula for Standard Deviation:
$$
\sqrt{\frac {\sum _{i=1}^{N}(x_{i}-{\overline {x}})^{2}}{N-1}}
$$

In [37]:
np.std(x2Array)

2.841730207648556

In [38]:
X2.std()

2.8427663900741122

In [39]:
df.std()

/var/folders/vg/knv8k4t949gbhzdyb1nl_p180000gn/T/ipykernel_13295/3390915376.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.std()


X2    2.842766
X3    5.869047
X4    4.310030
X5    2.101013
X6    0.491398
dtype: float64

Formula for Variance:
$$
\frac {\sum _{i=1}^{N}(x_{i}-{\overline {x}})^{2}}{N-1}
$$

In [40]:
np.var(x2Array)

8.075430573062306

In [41]:
X2.var()

8.081320748535

In [42]:
df.var()

/var/folders/vg/knv8k4t949gbhzdyb1nl_p180000gn/T/ipykernel_13295/1568254755.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.var()


X2     8.081321
X3    34.445710
X4    18.576359
X5     4.414256
X6     0.241472
dtype: float64

#### pandas Method

In [43]:
df.describe()

X2           X3           X4           X5           X6
count  1372.000000  1372.000000  1372.000000  1372.000000  1372.000000
mean      0.433665     1.922353     1.397627    -1.191657     0.406706
std       2.842766     5.869047     4.310030     2.101013     0.491398
min      -7.042100   -13.773100    -5.286100    -8.548200     0.000000
25%      -1.773000    -1.708200    -1.574975    -2.413450     0.000000
50%       0.496180     2.319650     0.616630    -0.586650     0.000000
75%       2.821475     6.814625     3.179250     0.394810     1.000000
max       6.824800    12.951600    17.927400     2.449500     1.000000

In [44]:
df.describe(include="all")

X1           X2           X3           X4           X5           X6
count    1372  1372.000000  1372.000000  1372.000000  1372.000000  1372.000000
unique   1372          NaN          NaN          NaN          NaN          NaN
top     P_001          NaN          NaN          NaN          NaN          NaN
freq        1          NaN          NaN          NaN          NaN          NaN
mean      NaN     0.433665     1.922353     1.397627    -1.191657     0.406706
std       NaN     2.842766     5.869047     4.310030     2.101013     0.491398
min       NaN    -7.042100   -13.773100    -5.286100    -8.548200     0.000000
25%       NaN    -1.773000    -1.708200    -1.574975    -2.413450     0.000000
50%       NaN     0.496180     2.319650     0.616630    -0.586650     0.000000
75%       NaN     2.821475     6.814625     3.179250     0.394810     1.000000
max       NaN     6.824800    12.951600    17.927400     2.449500     1.000000

### Load Sales data

In [45]:
salesData = pd.read_excel("dataFiles/Sales_Data.xlsx")
salesData

ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0           10107               30      95.70                2  2871.00   
1           10121               34      81.35                5  2765.90   
2           10134               41      94.74                2  3884.34   
3           10145               45      83.26                6  3746.70   
4           10168               36      96.66                1  3479.76   
...           ...              ...        ...              ...      ...   
2742        10350               20     112.22               15  2244.40   
2743        10373               29     137.19                1  3978.51   
2744        10386               43     125.99                4  5417.57   
2745        10397               34      62.24                1  2116.16   
2746        10414               47      65.52                9  3079.44   

      ORDERDATE  DAYS_SINCE_LASTORDER    STATUS  PRODUCTLINE  MSRP  \
0    2018-02-24                   828   Shipped  Motorcycles    95   
1    2018-05-07                   757   Shipped  Motorcycles    95   
2    2018-07-01                   703   Shipped  Motorcycles    95   
3    2018-08-25                   649   Shipped  Motorcycles    95   
4    2018-10-28                   586   Shipped  Motorcycles    95   
...         ...                   ...       ...          ...   ...   
2742 2019-12-02                  2924   Shipped        Ships    54   
2743 2020-01-31                  2865   Shipped        Ships    54   
2744 2020-03-01                  2836  Resolved        Ships    54   
2745 2020-03-28                  2810   Shipped        Ships    54   
2746 2020-05-06                  2772   On Hold        Ships    54   

     PRODUCTCODE             CUSTOMERNAME             PHONE  \
0       S10_1678        Land of Toys Inc.        2125557818   
1       S10_1678       Reims Collectables        26.47.1555   
2       S10_1678          Lyon Souveniers  +33 1 46 62 7555   
3       S10_1678        Toys4GrownUps.com        6265557265   
4       S10_1678     Technics Stores Inc.        6505556809   
...          ...                      ...               ...   
2742    S72_3212    Euro Shopping Channel    (91) 555 94 44   
2743    S72_3212  Oulu Toy Supplies, Inc.        981-443655   
2744    S72_3212    Euro Shopping Channel    (91) 555 94 44   
2745    S72_3212             Alpha Cognac        61.77.6555   
2746    S72_3212        Gifts4AllAges.com        6175559555   

                       ADDRESSLINE1        CITY POSTALCODE  COUNTRY  \
0           897 Long Airport Avenue         NYC      10022      USA   
1                59 rue de l'Abbaye       Reims      51100   France   
2     27 rue du Colonel Pierre Avia       Paris      75508   France   
3                78934 Hillside Dr.    Pasadena      90003      USA   
4                 9408 Furth Circle  Burlingame      94217      USA   
...                             ...         ...        ...      ...   
2742             C/ Moralzarzal, 86      Madrid      28034    Spain   
2743                    Torikatu 38        Oulu      90110  Finland   
2744             C/ Moralzarzal, 86      Madrid      28034    Spain   
2745          1 rue Alsace-Lorraine    Toulouse      31000   France   
2746             8616 Spinnaker Dr.      Boston      51003      USA   

     CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE  
0                 Yu             Kwai    Small  
1            Henriot             Paul    Small  
2           Da Cunha           Daniel   Medium  
3              Young            Julie   Medium  
4             Hirano             Juri   Medium  
...              ...              ...      ...  
2742          Freyre            Diego    Small  
2743       Koskitalo           Pirkko   Medium  
2744          Freyre            Diego   Medium  
2745          Roulet          Annette    Small  
2746         Yoshido             Juri   Medium  

[2747 rows x 20 columns]

In [46]:
salesData.shape

(2747, 20)

In [47]:
salesData.columns

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'DAYS_SINCE_LASTORDER', 'STATUS', 'PRODUCTLINE',
       'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE', 'ADDRESSLINE1', 'CITY',
       'POSTALCODE', 'COUNTRY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE'],
      dtype='object')

In [49]:
salesData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2747 entries, 0 to 2746
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   ORDERNUMBER           2747 non-null   int64         
 1   QUANTITYORDERED       2747 non-null   int64         
 2   PRICEEACH             2747 non-null   float64       
 3   ORDERLINENUMBER       2747 non-null   int64         
 4   SALES                 2747 non-null   float64       
 5   ORDERDATE             2747 non-null   datetime64[ns]
 6   DAYS_SINCE_LASTORDER  2747 non-null   int64         
 7   STATUS                2747 non-null   object        
 8   PRODUCTLINE           2747 non-null   object        
 9   MSRP                  2747 non-null   int64         
 10  PRODUCTCODE           2747 non-null   object        
 11  CUSTOMERNAME          2747 non-null   object        
 12  PHONE                 2747 non-null   object        
 13  ADDRESSLINE1      

In [48]:
numCol = []
catCol = []

for col in salesData.columns:
    if salesData[col].dtype == 'O':
        catCol.append(col)
    else:
        numCol.append(col)

In [50]:
print("List of categorical columns:", catCol)
print("List of numerical columns:", numCol)

List of categorical columns: ['STATUS', 'PRODUCTLINE', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE', 'ADDRESSLINE1', 'CITY', 'POSTALCODE', 'COUNTRY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME', 'DEALSIZE']
List of numerical columns: ['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER', 'SALES', 'ORDERDATE', 'DAYS_SINCE_LASTORDER', 'MSRP']


In [51]:
salesData.describe()

ORDERNUMBER  QUANTITYORDERED    PRICEEACH  ORDERLINENUMBER  \
count   2747.000000      2747.000000  2747.000000      2747.000000   
mean   10259.761558        35.103021   101.098951         6.491081   
std       91.877521         9.762135    42.042548         4.230544   
min    10100.000000         6.000000    26.880000         1.000000   
25%    10181.000000        27.000000    68.745000         3.000000   
50%    10264.000000        35.000000    95.550000         6.000000   
75%    10334.500000        43.000000   127.100000         9.000000   
max    10425.000000        97.000000   252.870000        18.000000   

              SALES  DAYS_SINCE_LASTORDER         MSRP  
count   2747.000000           2747.000000  2747.000000  
mean    3553.047583           1757.085912   100.691664  
std     1838.953901            819.280576    40.114802  
min      482.130000             42.000000    33.000000  
25%     2204.350000           1077.000000    68.000000  
50%     3184.800000           1761.000000    99.000000  
75%     4503.095000           2436.500000   124.000000  
max    14082.800000           3562.000000   214.000000

In [52]:
salesData[numCol].describe()

ORDERNUMBER  QUANTITYORDERED    PRICEEACH  ORDERLINENUMBER  \
count   2747.000000      2747.000000  2747.000000      2747.000000   
mean   10259.761558        35.103021   101.098951         6.491081   
std       91.877521         9.762135    42.042548         4.230544   
min    10100.000000         6.000000    26.880000         1.000000   
25%    10181.000000        27.000000    68.745000         3.000000   
50%    10264.000000        35.000000    95.550000         6.000000   
75%    10334.500000        43.000000   127.100000         9.000000   
max    10425.000000        97.000000   252.870000        18.000000   

              SALES  DAYS_SINCE_LASTORDER         MSRP  
count   2747.000000           2747.000000  2747.000000  
mean    3553.047583           1757.085912   100.691664  
std     1838.953901            819.280576    40.114802  
min      482.130000             42.000000    33.000000  
25%     2204.350000           1077.000000    68.000000  
50%     3184.800000           1761.000000    99.000000  
75%     4503.095000           2436.500000   124.000000  
max    14082.800000           3562.000000   214.000000

In [54]:
salesData[catCol].describe().T

count unique                    top  freq
STATUS            2747      6                Shipped  2541
PRODUCTLINE       2747      7           Classic Cars   949
PRODUCTCODE       2747    109               S18_3232    51
CUSTOMERNAME      2747     89  Euro Shopping Channel   259
PHONE             2747     88         (91) 555 94 44   259
ADDRESSLINE1      2747     89     C/ Moralzarzal, 86   259
CITY              2747     71                 Madrid   304
POSTALCODE        2747     73                  28034   259
COUNTRY           2747     19                    USA   928
CONTACTLASTNAME   2747     76                 Freyre   259
CONTACTFIRSTNAME  2747     72                  Diego   259
DEALSIZE          2747      3                 Medium  1349

In [55]:
salesData.describe(include="all")

/var/folders/vg/knv8k4t949gbhzdyb1nl_p180000gn/T/ipykernel_13295/1674680024.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  salesData.describe(include="all")


ORDERNUMBER  QUANTITYORDERED    PRICEEACH  ORDERLINENUMBER  \
count    2747.000000      2747.000000  2747.000000      2747.000000   
unique           NaN              NaN          NaN              NaN   
top              NaN              NaN          NaN              NaN   
freq             NaN              NaN          NaN              NaN   
first            NaN              NaN          NaN              NaN   
last             NaN              NaN          NaN              NaN   
mean    10259.761558        35.103021   101.098951         6.491081   
std        91.877521         9.762135    42.042548         4.230544   
min     10100.000000         6.000000    26.880000         1.000000   
25%     10181.000000        27.000000    68.745000         3.000000   
50%     10264.000000        35.000000    95.550000         6.000000   
75%     10334.500000        43.000000   127.100000         9.000000   
max     10425.000000        97.000000   252.870000        18.000000   

               SALES            ORDERDATE  DAYS_SINCE_LASTORDER   STATUS  \
count    2747.000000                 2747           2747.000000     2747   
unique           NaN                  246                   NaN        6   
top              NaN  2018-11-14 00:00:00                   NaN  Shipped   
freq             NaN                   38                   NaN     2541   
first            NaN  2018-01-06 00:00:00                   NaN      NaN   
last             NaN  2020-05-31 00:00:00                   NaN      NaN   
mean     3553.047583                  NaN           1757.085912      NaN   
std      1838.953901                  NaN            819.280576      NaN   
min       482.130000                  NaN             42.000000      NaN   
25%      2204.350000                  NaN           1077.000000      NaN   
50%      3184.800000                  NaN           1761.000000      NaN   
75%      4503.095000                  NaN           2436.500000      NaN   
max     14082.800000                  NaN           3562.000000      NaN   

         PRODUCTLINE         MSRP PRODUCTCODE           CUSTOMERNAME  \
count           2747  2747.000000        2747                   2747   
unique             7          NaN         109                     89   
top     Classic Cars          NaN    S18_3232  Euro Shopping Channel   
freq             949          NaN          51                    259   
first            NaN          NaN         NaN                    NaN   
last             NaN          NaN         NaN                    NaN   
mean             NaN   100.691664         NaN                    NaN   
std              NaN    40.114802         NaN                    NaN   
min              NaN    33.000000         NaN                    NaN   
25%              NaN    68.000000         NaN                    NaN   
50%              NaN    99.000000         NaN                    NaN   
75%              NaN   124.000000         NaN                    NaN   
max              NaN   214.000000         NaN                    NaN   

                 PHONE        ADDRESSLINE1    CITY POSTALCODE COUNTRY  \
count             2747                2747    2747       2747    2747   
unique              88                  89      71         73      19   
top     (91) 555 94 44  C/ Moralzarzal, 86  Madrid      28034     USA   
freq               259                 259     304        259     928   
first              NaN                 NaN     NaN        NaN     NaN   
last               NaN                 NaN     NaN        NaN     NaN   
mean               NaN                 NaN     NaN        NaN     NaN   
std                NaN                 NaN     NaN        NaN     NaN   
min                NaN                 NaN     NaN        NaN     NaN   
25%                NaN                 NaN     NaN        NaN     NaN   
50%                NaN                 NaN     NaN        NaN     NaN   
75%                NaN                 NaN     NaN        NaN   

### Loading honeyProduction.csv

In [56]:
honeyproduction = pd.read_csv("honeyproduction.csv")
honeyproduction.head()

state    numcol  yieldpercol   totalprod      stocks  priceperlb  \
0    AL   16000.0           71   1136000.0    159000.0        0.72   
1    AZ   55000.0           60   3300000.0   1485000.0        0.64   
2    AR   53000.0           65   3445000.0   1688000.0        0.59   
3    CA  450000.0           83  37350000.0  12326000.0        0.62   
4    CO   27000.0           72   1944000.0   1594000.0        0.70   

    prodvalue  year  
0    818000.0  1998  
1   2112000.0  1998  
2   2033000.0  1998  
3  23157000.0  1998  
4   1361000.0  1998

In [57]:
honeyproduction.shape

(626, 8)

In [58]:
honeyproduction.columns

Index(['state', 'numcol', 'yieldpercol', 'totalprod', 'stocks', 'priceperlb',
       'prodvalue', 'year'],
      dtype='object')

In [59]:
honeyproduction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 626 entries, 0 to 625
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   state        626 non-null    object 
 1   numcol       626 non-null    float64
 2   yieldpercol  626 non-null    int64  
 3   totalprod    626 non-null    float64
 4   stocks       626 non-null    float64
 5   priceperlb   626 non-null    float64
 6   prodvalue    626 non-null    float64
 7   year         626 non-null    int64  
dtypes: float64(5), int64(2), object(1)
memory usage: 39.2+ KB


In [60]:
numCol = []
catCol = []

for col in honeyproduction.columns:
    if honeyproduction[col].dtype == 'O':
        catCol.append(col)
    else:
        numCol.append(col)

In [61]:
print("List of categorical columns:", catCol)
print("List of numerical columns:", numCol)

List of categorical columns: ['state']
List of numerical columns: ['numcol', 'yieldpercol', 'totalprod', 'stocks', 'priceperlb', 'prodvalue', 'year']


In [63]:
honeyproduction[catCol].describe()

state
count    626
unique    44
top       AL
freq      15

In [64]:
honeyproduction[numCol].describe()

numcol  yieldpercol     totalprod        stocks  priceperlb  \
count     626.000000   626.000000  6.260000e+02  6.260000e+02  626.000000   
mean    60284.345048    62.009585  4.169086e+06  1.318859e+06    1.409569   
std     91077.087231    19.458754  6.883847e+06  2.272964e+06    0.638599   
min      2000.000000    19.000000  8.400000e+04  8.000000e+03    0.490000   
25%      9000.000000    48.000000  4.750000e+05  1.430000e+05    0.932500   
50%     26000.000000    60.000000  1.533000e+06  4.395000e+05    1.360000   
75%     63750.000000    74.000000  4.175250e+06  1.489500e+06    1.680000   
max    510000.000000   136.000000  4.641000e+07  1.380000e+07    4.150000   

          prodvalue         year  
count  6.260000e+02   626.000000  
mean   4.715741e+06  2004.864217  
std    7.976110e+06     4.317306  
min    1.620000e+05  1998.000000  
25%    7.592500e+05  2001.000000  
50%    1.841500e+06  2005.000000  
75%    4.703250e+06  2009.000000  
max    6.961500e+07  2012.000000

In [62]:
honeyproduction.describe(include="all")

state         numcol  yieldpercol     totalprod        stocks  \
count    626     626.000000   626.000000  6.260000e+02  6.260000e+02   
unique    44            NaN          NaN           NaN           NaN   
top       AL            NaN          NaN           NaN           NaN   
freq      15            NaN          NaN           NaN           NaN   
mean     NaN   60284.345048    62.009585  4.169086e+06  1.318859e+06   
std      NaN   91077.087231    19.458754  6.883847e+06  2.272964e+06   
min      NaN    2000.000000    19.000000  8.400000e+04  8.000000e+03   
25%      NaN    9000.000000    48.000000  4.750000e+05  1.430000e+05   
50%      NaN   26000.000000    60.000000  1.533000e+06  4.395000e+05   
75%      NaN   63750.000000    74.000000  4.175250e+06  1.489500e+06   
max      NaN  510000.000000   136.000000  4.641000e+07  1.380000e+07   

        priceperlb     prodvalue         year  
count   626.000000  6.260000e+02   626.000000  
unique         NaN           NaN          NaN  
top            NaN           NaN          NaN  
freq           NaN           NaN          NaN  
mean      1.409569  4.715741e+06  2004.864217  
std       0.638599  7.976110e+06     4.317306  
min       0.490000  1.620000e+05  1998.000000  
25%       0.932500  7.592500e+05  2001.000000  
50%       1.360000  1.841500e+06  2005.000000  
75%       1.680000  4.703250e+06  2009.000000  
max       4.150000  6.961500e+07  2012.000000