In [1]:
import numpy as np

### Creating Arrays

In [2]:
a = np.array([2, 3, 4, 5])
a

array([2, 3, 4, 5])

In [3]:
a.dtype

dtype('int32')

In [4]:
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [6]:
b.dtype

dtype('float64')

In [7]:
c = np.array([(1.5, 2, 3), (4, 5, 6)])
c

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [8]:
c.dtype

dtype('float64')

In [9]:
# np.zeros(rows, columns)
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [13]:
d = np.arange(0, 50, 5)
d

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
e = np.arange(0, 1, 0.1)
e

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [17]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
d.reshape(2,5)

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

### Mathematical operations

In [19]:
d

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [20]:
d + 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [22]:
d * 10

array([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450])

In [23]:
d - 5

array([-5,  0,  5, 10, 15, 20, 25, 30, 35, 40])

In [24]:
d / 5

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [25]:
(d + 5) / 5

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
np.sin(d)

array([ 0.        , -0.95892427, -0.54402111,  0.65028784,  0.91294525,
       -0.13235175, -0.98803162, -0.42818267,  0.74511316,  0.85090352])

In [29]:
print(d)
print(e)
print(d * e)

[ 0  5 10 15 20 25 30 35 40 45]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[ 0.   0.5  2.   4.5  8.  12.5 18.  24.5 32.  40.5]


### Indexing and slicing

In [30]:
d

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [31]:
d[8]

40

In [32]:
d[2:5]

array([10, 15, 20])

In [33]:
d[-1]

45

In [34]:
d[-3:]

array([35, 40, 45])

### Numpy Functions

In [35]:
f = d.copy()

In [38]:
d

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [37]:
f = f + 5
f

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [39]:
f.sum()

275

In [40]:
f.min()

5

In [41]:
f.max()

50

In [42]:
f.mean()

27.5

In [43]:
f.std()

14.361406616345072

In [44]:
g = d.reshape(2,5)
g

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [45]:
g.max(axis=0)

array([25, 30, 35, 40, 45])

In [46]:
g.max(axis=1)

array([20, 45])

In [47]:
f

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [49]:
h = np.where(f >= 25, f == 0, f)
h

array([ 5, 10, 15, 20,  0,  0,  0,  0,  0,  0])

In [50]:
i = np.random.rand(3,2)
i

array([[0.75625785, 0.13723004],
       [0.87187095, 0.21784921],
       [0.42863547, 0.91569164]])

In [52]:
j = np.where(i <= 0.5, i == 0, i)
j

array([[0.75625785, 0.        ],
       [0.87187095, 0.        ],
       [0.        , 0.91569164]])