# Python Numpy

In [1]:
import numpy as np

In [4]:
# 1. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

arr = np.arange(100,200,10).reshape(5,2)
print(arr)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [17]:
# 2. Write a NumPy program to create a 3x3x3 array filled with arbitrary values and find the minimum and maximum values.

arr1 = np.random.randint(2, 20, (3, 3, 3))
print(arr1)
print("Min:", arr1.min())
print("Max:", arr1.max())

[[[18  8  4]
  [ 9 11  2]
  [ 5 15 10]]

 [[10  6 10]
  [ 9 13  7]
  [ 4  7 18]]

 [[12 13 16]
  [11  8  9]
  [10 13 18]]]
Min: 2
Max: 18


In [20]:
# 3. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

arr2 = np.diag([1,2,3,4,5])
print(arr2)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [26]:
# 4. Given an array arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9 i) Extract all odd numbers from arr ii) Replace all odd numbers in arr with -1.

arr3 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr3)
modified = np.where(arr3 % 2 == 1, -1, arr3)
print(modified)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [28]:
# 5.Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1,the rest are 0.

arr4 = np.eye(3,3)
print(arr4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
# 6. Write a NumPy program to convert an array to a float type.

arr5 = np.array([1,5,8,9,0,3,6])
print(arr5)
conv = arr5.astype(float)
print(conv)
a = np.asfarray(arr5)
print(a)

[1 5 8 9 0 3 6]
[1. 5. 8. 9. 0. 3. 6.]
[1. 5. 8. 9. 0. 3. 6.]


In [35]:
# 7. Write a NumPy program to generate five random numbers from the normal distribution.

arr6 = np.random.normal(size = 5)
print(arr6)

[ 0.04485434 -0.20276354 -1.90366849  0.42592204 -0.49358124]


In [48]:
# 8. Following is the input NumPy array delete column two and insert following new column in its place.
# sampleArray=numpy.array([[34,43,73],[82,22,12],[53,94,66]]) newColumn = numpy.array([[10,10,10]])

arr7 = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print(" Original:",arr7)
del_arr = np.delete(arr7, 2, axis=1)
print("\n Deleted:", del_arr)
ins_arr = np.insert(del_arr, [2], [[10],[10],[10]], axis = 1)
print("\n Inserted:", ins_arr)

 Original: [[34 43 73]
 [82 22 12]
 [53 94 66]]

 Deleted: [[34 43]
 [82 22]
 [53 94]]

 Inserted: [[34 43 10]
 [82 22 10]
 [53 94 10]]


In [53]:
# 9. Write a NumPy program to compute the multiplicationof two given matrices.

arr_m1 = np.array([[3,4,7],[8,2,1],[5,9,6]]) 
arr_m2 = np.array([[5,9,6],[8,2,1],[3,4,7]]) 
print(" Original: \n", arr_m1, "\n \n", arr_m2), 
ar_mul = np.multiply(arr_m1,arr_m2)
print("\n Multiplied: \n", ar_mul)

 Original: 
 [[3 4 7]
 [8 2 1]
 [5 9 6]] 
 
 [[5 9 6]
 [8 2 1]
 [3 4 7]]

 Multiplied: 
 [[15 36 42]
 [64  4  1]
 [15 36 42]]


In [77]:
# 10. Write a NumPy program to create a random vector of size 10 and sort it.

vect = np.random.random(10)
print(" Original: \n", vect, "\n")
vect.sort()
print(" Sorted: \n", vect)

 Original: 
 [0.92859181 0.73247215 0.37194365 0.72991393 0.58258988 0.24710347
 0.93917366 0.23591221 0.84642944 0.34571666] 

 Sorted: 
 [0.23591221 0.24710347 0.34571666 0.37194365 0.58258988 0.72991393
 0.73247215 0.84642944 0.92859181 0.93917366]


In [79]:
# 11. Write a NumPy program to compute the covariance matrix of two arrays.

arr9 = np.array([2, 5, 1, 7])
arr8 = np.array([3, 4, 2, 1])
  
print(" Original: \n", arr9, "\n", arr8)

# Covariance matrix
print("\nCovariance matrix:\n", np.cov(arr9, arr8))


 Original: 
 [2 5 1 7] 
 [3 4 2 1]

Covariance matrix:
 [[ 7.58333333 -0.83333333]
 [-0.83333333  1.66666667]]


In [91]:
# 12.Create a 4X2 integer array and Prints its: i)The shape of an array. ii) Array dimensions. iii) The Length of each element of the array in bytes

arr10 = np.arange(1,9).reshape(4,2)
print(arr10)
print("Shape: ", arr10.shape)
print("Dimension: ", arr10.ndim)
print("Length in Bytes: ", arr10.itemsize)
print("Total Bytes: ", arr10.nbytes)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape:  (4, 2)
Dimension:  2
Length in Bytes:  4
Total Bytes:  32


In [98]:
# 14. Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array.

arr11 = np.array(['Data', 'folks', 'Institution'], dtype=np.str)
print("Original Array: ", arr11)
capitalized = np.char.capitalize(arr11)
lowered = np.char.lower(arr11)
uppered = np.char.upper(arr11)
swapcased = np.char.swapcase(arr11)
titlecased = np.char.title(arr11)
print("\nCapitalized: ", capitalized)
print("Lowered: ", lowered)
print("Uppered: ", uppered)
print("Swapcased: ", swapcased)
print("Titlecased: ", titlecased)

Original Array:  ['Data' 'folks' 'Institution']

Capitalized:  ['Data' 'Folks' 'Institution']
Lowered:  ['data' 'folks' 'institution']
Uppered:  ['DATA' 'FOLKS' 'INSTITUTION']
Swapcased:  ['dATA' 'FOLKS' 'iNSTITUTION']
Titlecased:  ['Data' 'Folks' 'Institution']


In [97]:
# 15. Write a NumPy program to convert a given array into a list.

arr12= np.arange(9).reshape(3, 3)
print("Original Array: \n", arr12, "\n")
print("Converted List: \n", arr12.tolist())

Original Array: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

Converted List: 
 [[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [104]:
# 16. Write a NumPy program to compute the sum of all elements, sum of each column and sum of each row of a given array.

arr13 = np.array([[4,0,1],[2,7,8]])
print("Original: \n",arr13)
print("Sum of all elements:")
print(np.sum(arr13))
print("Sum of each column:")
print(np.sum(arr13, axis=0))
print("Sum of each row:")
print(np.sum(arr13, axis=1))

Original: 
 [[4 0 1]
 [2 7 8]]
Sum of all elements:
22
Sum of each column:
[6 7 9]
Sum of each row:
[ 5 17]


In [105]:
# 17. Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable

arr14 = np.random.rand(10, 4)
print("Original array: ")
print(arr14)
y= arr14[:5, :]
print(" \n First 5 rows of the above array:")
print(y)

Original array: 
[[0.20437072 0.95239205 0.72458165 0.49035805]
 [0.72407427 0.26595391 0.7220097  0.05424474]
 [0.68611372 0.64846109 0.73583258 0.42374227]
 [0.50722217 0.06012705 0.75108592 0.15717428]
 [0.09590191 0.81835719 0.28198852 0.9484446 ]
 [0.9998656  0.42579109 0.7770542  0.5380094 ]
 [0.7592773  0.75119787 0.01479293 0.6793843 ]
 [0.38724801 0.62816798 0.91241836 0.77548538]
 [0.3936262  0.97446965 0.90777865 0.85408534]
 [0.22964231 0.4507451  0.35120318 0.33554091]]
 
 First 5 rows of the above array:
[[0.20437072 0.95239205 0.72458165 0.49035805]
 [0.72407427 0.26595391 0.7220097  0.05424474]
 [0.68611372 0.64846109 0.73583258 0.42374227]
 [0.50722217 0.06012705 0.75108592 0.15717428]
 [0.09590191 0.81835719 0.28198852 0.9484446 ]]


In [107]:
# 18. Write a NumPy program to get the unique elements of a 1D and 2D array.

arr14 = np.array([10, 10, 20, 20, 30, 30, 40])
print("1D array: \n", arr14)
print("Unique elements of 1D array: \n", np.unique(arr14), "\n")
arr15 = np.array([[1, 1, 7], [2, 2, 3]])
print("2D array: \n", arr15)
print("Unique elements of 2D array: \n", np.unique(arr15))

1D array: 
 [10 10 20 20 30 30 40]
Unique elements of 1D array: 
 [10 20 30 40] 

2D array: 
 [[1 1 7]
 [2 2 3]]
Unique elements of 2D array: 
 [1 2 3 7]


In [110]:
# 19. Write a NumPy program to get the unique elements of an array. arr= [ -10 12.12 -0.2]

arr16 = np.array([-10, 12.12, -0.2])
np.unique(arr16)

array([-10.  ,  -0.2 ,  12.12])

In [115]:
# 20. Write a NumPy program to save a given array to a text file and load it. You have to save and load files using numpy library.

arr17 = np.arange(10).reshape(2, 5)
print("Original array: \n" ,arr17)
np.savetxt('temp.txt', arr17 , fmt="%d") 
print("After loading, content of the text file:")
textfile = np.loadtxt('temp.txt')
print(textfile)

Original array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
After loading, content of the text file:
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
